# Replace with your values. Example:
# kubectl create secret generic airflow-secret -n task2-analytics \
#   --from-literal=POSTGRES_PASSWORD=airflow \
#   --from-literal=MONGODB_URI='mongodb://root:example@mongodb.task2-app.svc.cluster.local:27017/?authSource=admin'
apiVersion: v1
kind: Secret
metadata:
  name: airflow-secret
  namespace: task2-analytics
type: Opaque
stringData:
  POSTGRES_PASSWORD: "airflow"
  MONGODB_URI: "mongodb://root:example@mongodb.task2-app.svc.cluster.local:27017/?authSource=admin"
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://airflow:airflow@postgres.task2-analytics.svc.cluster.local:5432/airflow"
