apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config
  namespace: task2-analytics
data:
  PG_HOST: "postgres"
  PG_PORT: "5432"
  PG_USER: "airflow"
  PG_ANALYTICS_DB: "analytics"
  MONGODB_DB: "sensors"
  MONGODB_COLLECTION: "measurements"
  MONGODB_SENSORS: "sensors"
  MONGODB_ALERTS: "alerts"
  SENSOR_API_URL: "http://sensor-service.task2-app.svc.cluster.local:8000"
