apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: task2-analytics
resources:
  - namespace.yaml
  - airflow-secret.yaml
  - airflow-configmap.yaml
  - airflow-variables-configmap.yaml
  - airflow-dags-configmap.yaml
  - postgres-pvc.yaml
  - postgres-init-configmap.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - airflow-db-init-job.yaml
  - airflow-webserver-deployment.yaml
  - airflow-webserver-service.yaml
  - airflow-scheduler-deployment.yaml
  - airflow-scheduler-service.yaml
