apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: task2-analytics
spec:
  accessModes:
    - ReadWriteOnce
  # StorageClass в кластере: fast.ru-7a (OpenStack Cinder). Для другого класса — kubectl get sc
  storageClassName: fast.ru-7a
  resources:
    requests:
      storage: 2Gi
