apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: task2-analytics
spec:
  accessModes:
    - ReadWriteOnce
  # Selectel: basic —
  storageClassName: basic
  resources:
    requests:
      storage: 2Gi
